# Generated by Django 6.1.1 on 2026-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_service_order_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('IN_PROGRESS', 'В работе'), ('READY', 'Готов'), ('COMPLETED', 'Выдан клиенту')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
